---
# Playbook to build GemStone package
# ansible-playbook 2_build_ppa.yml --extra-vars "version=3.7.0 priority=30700"
#

- name: Build GemStone packages for Linux (amd64 and arm64)
  hosts: pitcairn
  vars:
    version: "3.7.0"
    priority: "30700"
    package_num: "1"
  tasks:
    - name: Install dpkg-dev package
      become: true
      ansible.builtin.apt:
        allow_change_held_packages: true
        install_recommends: true
        name: dpkg-dev
        state: latest
        update_cache: true
    - name: Install fakeroot package
      become: true
      ansible.builtin.apt:
        allow_change_held_packages: true
        install_recommends: true
        name: fakeroot
        state: latest
    - name: Install unzip package
      become: true
      ansible.builtin.apt:
        allow_change_held_packages: true
        install_recommends: true
        name: unzip
        state: latest
    - name: Git checkout of Debian package building repository
      ansible.builtin.git:
        repo: https://github.com/jgfoster/gemstone_deb.git
        accept_newhostkey: true
        depth: 1
        force: true
        single_branch: true
        dest: /pitcairn1/users/jfoster/gemstone_deb
        update: true
        version: pitcairn
    - name: Build amd64 package
      ansible.builtin.shell: |
        cd /pitcairn1/users/jfoster/gemstone_deb
        export VERSION="{{ version }}"
        export PRIORITY="{{ priority }}"
        export PACKAGE_NUM="{{ package_num }}"
        export ARCHITECTURE="amd64"
        ./build.sh
    - name: Build arm64 package
      ansible.builtin.shell: |
        cd /pitcairn1/users/jfoster/gemstone_deb
        export VERSION="{{ version }}"
        export PRIORITY="{{ priority }}"
        export PACKAGE_NUM="{{ package_num }}"
        export ARCHITECTURE="arm64"
        ./build.sh
