---
# Playbook to build GemStone repository
# https://www.digitalocean.com/community/tutorials/how-to-use-reprepro-for-a-secure-package-repository-on-ubuntu-14-04
# ansible-playbook 3_build_repo.yml
#

- name: Build GemStone repository
  hosts: pitcairn
  tasks:
    - name: Install reprepro package
      become: true
      ansible.builtin.apt:
        allow_change_held_packages: true
        install_recommends: true
        name: reprepro
        state: latest
        update_cache: true
        cache_valid_time: 300
    - name: Create ppa and conf directories
      ansible.builtin.file:
        path: /pitcairn1/users/jfoster/ppa/conf
        state: directory
        mode: '0755'
    - name: Copy distributions file
      ansible.builtin.copy:
        src: ./distributions
        dest: /pitcairn1/users/jfoster/ppa/conf/distributions
    - name: Get names of packages
      ansible.builtin.shell: ls /pitcairn1/users/jfoster/gemstone-server*.deb
      register: file_names
      changed_when: false
    - name: Add packages to repository
      ansible.builtin.shell: reprepro -b /pitcairn1/users/jfoster/ppa includedeb stable {{ item }}
      loop: "{{ file_names.stdout_lines }}"
    - name: Copy dists to PPA
      ansible.builtin.shell: rsync -rlpt --delete -e "ssh -p 2222" /pitcairn1/users/jfoster/ppa/dists/ ubuntu@alpha-ppa.gemtalksystems.com:/srv/ppa/alpha/dists
    - name: Copy pool to PPA
      ansible.builtin.shell: rsync -rlpt --delete -e "ssh -p 2222" /pitcairn1/users/jfoster/ppa/pool/ ubuntu@alpha-ppa.gemtalksystems.com:/srv/ppa/alpha/pool
