#!/bin/sh -e
# data stored in /var/cache/debconf/
# https://www.debian.org/releases/stretch/amd64/apb.html.en

. /usr/share/debconf/confmodule

if [ ! -f /etc/gemstone/secret ]; then
  db_input critical gemstone-server/password || true
  db_input critical gemstone-server/password-confirm || true
fi
db_input high gemstone-server/unicode-comparison || true
db_go || true

if [ -f /etc/gemstone/secret ]; then
  exit 0
fi

db_get gemstone-server/password
password1=$RET
db_get gemstone-server/password-confirm
password2=$RET
if [ "$password1" != "$password2" ]; then
  db_unregister gemstone-server/password || true
  db_unregister gemstone-server/password-confirm || true
  >&2 echo "Passwords must match!"
  exit 1
fi
if [ "-$password1-" = "--" ]; then
  db_unregister gemstone-server/password || true
  db_unregister gemstone-server/password-confirm || true
  >&2 echo "Passwords must not be empty!"
  exit 1
fi
exit 0
