#!/bin/sh -e
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
# >&2 echo "\"$0\" \"$1\" \"$2\" \"$3\""

. /usr/share/debconf/confmodule

# is there another installation of GemStone?
keep="0"
if [ -d "/usr/lib/gemstone" ]; then
  if [ "$(ls -A /usr/lib/gemstone/)" ]; then
    keep="1"
  fi
fi
# if no other versions of GemStone...
if [ "$keep" = "0" ]; then
  # remove GemStone NetLDI from services
  x=`grep gs64ldi /etc/services` || true
  if [ ! -z "$x" ]; then
    sed -i '\:gs64ldi   50377/tcp   # GemStone/S 64 Bit:d' /etc/services
  fi
  # remove GEMSTONE environment variables
  x=`grep GEMSTONE /etc/environment` || true
  if [ ! -z "$x" ]; then
    sed -i '\:GEMSTONE=/usr/lib/gemstone/VERSION:d' /etc/environment
    sed -i '\:GEMSTONE_GLOBAL_DIR=/var/lib/gemstone:d' /etc/environment
  fi
  if [ "$1" = "purge" ]; then
    rm -rf /etc/gemstone/secret /run/gemstone /var/lib/gemstone /var/log/gemstone
    deluser gemstone || true
    rm -rf /home/gemstone
    db_purge || true
  fi
fi

exit 0 # if we got here then all went well!
