#!/bin/bash
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
set -e
# echo "\"$0\" \"$1\" \"$2\" \"$3\""

# stop GemStone services
systemctl stop gs64ldi
systemctl stop gs64stone

# remove alternatives - https://manpages.ubuntu.com/manpages/jammy/en/man1/update-alternatives.1.html
update-alternatives --remove gemstone /usr/lib/gemstone/VERSION

exit 0 # if we got here then all went well!
