#!/bin/sh -e
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
# >&2 echo "\"$0\" \"$1\" \"$2\" \"$3\""

. /usr/share/debconf/confmodule

# stop GemStone services
systemctl stop gs64ldi || true
systemctl stop gs64stone || true

# remove alternatives - https://manpages.ubuntu.com/manpages/jammy/en/man1/update-alternatives.1.html
update-alternatives --remove gemstone /usr/lib/gemstone/VERSION || true

exit 0 # if we got here then all went well!
